version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/server
    command: air main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - LANG=en_NZ.utf8
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgres/data
volumes:
  postgres-db:
